# starting with CentOS7, create a container for the bot: Keats.
#
#  Start by adding all the OS level libraries required.
#
#  Notice: this uses epel-release files!!
#
FROM rossgore/python-env-cci:latest
USER root
RUN mkdir /home/app
WORKDIR /home/app

# if you want to check your work, run the container
# start R, and source this file
COPY ./ ./

USER root

# last, run this script to install all of the R dependecies
RUN chmod +x run_python_connectivity_test.sh

ENTRYPOINT ./run_python_connectivity_test.sh
